server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teaching_platform?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    username: root
    password: "010629"
  redis:
    host: localhost
    port: 6379
  mvc:
    dispatch-options-request: true
    pathmatch:
      # Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      # 所以需要配置此参数
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
